### ISSUE TITLE
请问下你是怎么访问到ibook的，在这里没有ibook的文件夹

### ISSUE THREAD

**Issue by ddshiyu** [JoeyBling/JoeyBling.github.io#31]
我用这个定义一个html文件，当还是会用到模板的样式，求指教

**Comment by JoeyBling** [comment]
> 我用这个定义一个html文件，当还是会用到模板的样式，求指教

另外的一个框架写的`vuepress`，只是在hexo这做了一个链接跳转哦，子站

**Comment by ddshiyu** [comment]
有一点没有理解子站的意思，，域名是一样的，，但是下面没有ibook的文件夹，

**Comment by JoeyBling** [comment]
> 有一点没有理解子站的意思，，域名是一样的，，但是下面没有ibook的文件夹，

通过映射不同路径代理跳转不同地址
我放在这个仓库的
> [https://github.com/JoeyBling/ibooks](https://github.com/JoeyBling/ibooks)

**Comment by ddshiyu** [comment]
可以截个图这个跳转的代码的图吗，，我也想做这个功能，，还是不太清除，，感谢了

**Comment by JoeyBling** [comment]
就是一个简单的HTML跳转链接而已，用的是[GH-pages](https://pages.github.com/)服务，你可以看gh的官方文档，不同仓库名访问的url根据仓库名而定

**Comment by ddshiyu** [comment]
ok ..非常感谢了

**Comment by ddshiyu** [comment]
可以了，原来是这个
